# Generated by Django 4.0.3 on 2022-05-17 11:06

import department.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduationYear',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2022)], verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='ITN',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(999999999999)], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.empfamily', verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='insPolicy',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10000000000000000), django.core.validators.MaxValueValidator(999999999999999999)], verbose_name='Номер мед. полиса'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='phoneNum',
            field=models.CharField(max_length=12, validators=[department.models.validate_phone, django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(12)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='snils',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(9999999999999999), department.models.validate_sninls], verbose_name='СНИЛС'),
        ),
    ]
