# Generated by Django 4.0.3 on 2022-05-17 11:08

import department.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_education_graduationyear_alter_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfile',
            name='snils',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14), department.models.validate_sninls], verbose_name='СНИЛС'),
        ),
    ]
