# Generated by Django 4.0.4 on 2022-05-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_personalfile_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfile',
            name='family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.empfamily', verbose_name='Семья'),
        ),
    ]
