# Generated by Django 4.0.5 on 2022-06-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_personalfile_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Вид приказа')),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(default='На рассмотрении', editable=False, max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца действия договора'),
        ),
    ]
