# Generated by Django 4.0.5 on 2022-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfile',
            name='orders',
            field=models.ManyToManyField(to='department.order', verbose_name='Приказы'),
        ),
    ]
